const { jsonToQueryString,queryStringToJson,resetString,snakeToCamel,camelToSnake,isArray,isObject,calculateClockDrift,Base64,reParseString,generateId,notifyMe,meta,sniffId,hideRandom,_rotateArray,_equals,_repeat } = require('./src/utils');
const waelioUtils = { jsonToQueryString,queryStringToJson,resetString,snakeToCamel,camelToSnake,isArray,isObject,calculateClockDrift,Base64,reParseString,generateId,notifyMe,meta,sniffId,hideRandom,_rotateArray,_equals,_repeat };

exports.jsonToQueryString = jsonToQueryString
exports.queryStringToJson = queryStringToJson
exports.resetString = resetString
exports.snakeToCamel = snakeToCamel
exports.camelToSnake = camelToSnake
exports.isArray = isArray
exports.isObject = isObject;
exports.calculateClockDrift = calculateClockDrift
exports.Base64 = Base64;
exports.reParseString = reParseString;
exports.generateId = generateId;
exports.notifyMe = notifyMe
exports.meta = meta
exports.sniffId = sniffId
exports.hideRandom = hideRandom
exports._rotateArray = _rotateArray
exports._equals = _equals
exports._repeat = _repeat
exports.waelioUtils = waelioUtils